---
version: 2
updates:
  - package-ecosystem: docker
    directory: /.devcontainer/
    schedule:
      interval: weekly
    target-branch: master
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /.devcontainer/
    schedule:
      interval: weekly
    target-branch: v9
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /.devcontainer/
    schedule:
      interval: weekly
    target-branch: v10
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /.devcontainer/
    schedule:
      interval: weekly
    target-branch: v11
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: master
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: v9
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: v10
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: v11
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: master
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: v9
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: v10
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: v11
    open-pull-requests-limit: 10
